### ISSUE TITLE
BufNMF has no padding argument.

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-core#111]
This was noticed by @tremblap and myself this morning. We were wondering if it is supposed to or not? And if so, if there's a plan for adding it.

**Comment by weefuzzy** [comment]
I've only just noticed this. It's by design, and I'm afraid PA must have forgotten the very long conversation about what did and didn't get a padding parameter when they got added. The only things with padding are the standard wrapped descriptors. Other FFT objects are all locked at a standard win / 2. I can see how a case for NMF being as much a descriptor as an audio object can be made, but the effort to reward ratio isn't good in this instance.
