### ISSUE TITLE
What are the BufNNDSVD `method`s?

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-core#165]
In the C++ code I found this:
```
  index process(RealMatrixView X, RealMatrixView W, RealMatrixView H,
                index minRank = 0, index maxRank = 200, double amount = 0.8,
                index method = 0) // 0 - NMF-SVD, 1 NNDSVDar, 2 NNDSVDa 3 NNDSVD
``` 
Which mostly correlates (although in a different order) to the options laid out in the [reference](http://nimfa.biolab.si/nimfa.methods.seeding.nndsvd.html):
```
options (dict) –
Specify the algorithm and model specific options (e.g. initialization of extra matrix factor, seeding parameters).

Option flag indicates the variant of the NNDSVD algorithm. It can take value from:

0 – NNDSVD,
1 – NNDSVDa (fill in the zero elements with the average),
2 – NNDSVDar (fill in the zero elements with random values in the space [0:average/100]).
Default is NNDSVD. Because of the nature of NNDSVDa and NNDSVDar, when the target matrix is sparse, only NNDSVD is possible and flag is ignored (NNDSVDa and NNDSVDar eliminate zero elements, therefore the matrix is not sparse anymore).
```
So I have a few questions:

- Are they in a different order for a reason?
- What is "NMF-SVD" as listed in our source code above?
- Why might someone choose one of these over another?

(I've investigated the [secondary reference](https://www.sciencedirect.com/science/article/abs/pii/S0031320307004359) and don't feel that I'll be able to cull the answers from it myself.)

**Comment by weefuzzy** [comment]
>  Are they in a different order for a reason?

Pass. Our first reference would have normally been the sklearn object, but our NNDSVD options are reversed with respect to that as well. 

>  What is "NMF-SVD" as listed in our source code above?

From what I can tell, it simply uses a round of SVD (which is the optimising on same basic condition as PCA) to initialise the NMF matrices and just gets to the non-negativity constraint by using the absolute value of the SVD matrices. This is likely to be quicker than the other options, but less rigorous. 

> Why might someone choose one of these over another?

The NNDSVD options all also start out by using SVD to get at an initial decomposition, but use a more principled trick to fulfil the non-negativity constraint. The authors of [2] discovered a neat trick with the result matrices that means that running a second, mini SVD on each of the decomposed matrices in turn yields something non-negative with better properties. The differences then lie in what is done with 0-values in the initial estimates. NNDSVD leaves them as they are, which promotes sparse results from the subsequent NMF (because, with multiplicative updates, 0s remain 0s). This may or may not be desirable (not least because sparsity implies the need for more components, but also the specific domain might imply that reasonable decomposition just isn't going to be sparse). 

The other two options then fill in the zeros differently. `NNDSVDa` uses a constant taken from the mean value of the source matrix. `NNDSVDar` uses small random values. The original paper didn't think there was much to choose between them, but sklearn claims the random values will be slightly faster but less accurate. 

I don't we have enough usage experience yet to be able to claim one as much superior to another. In general they should all substantially increase the speed with which NMF converges, and avoid especially poor local minima.
