### ISSUE TITLE
MelBands features buffer contains many zeros

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-core#84]
I noticed that some combinations of `numBands` and `windowSize` (i.e., `fftSize`) writes a lot of zeros into the features buffer. In a FluidWaveform these show up as black bars.

<img width="1712" alt="Screenshot 2022-01-20 at 14 03 08" src="https://user-images.githubusercontent.com/1531144/150405928-2a8264aa-7a29-48cc-ad48-355180f5a4e4.png">

I poked at it a bit (see below). I'm guessing this has to do with the scaling that's happening under the hood, but it feel like a mistake. 
* Can the channels that would be all zeros just be removed (but of course then it would have fewer channels than requested `numBands`)? 
* Or can the useful values be copied into the channels that would have all zeros (so that the image can be correct)? 
* Or is this a different underlying issue?

```
s.boot;

~drums = Buffer.read(s,FluidFilesPath("Nicol-LoopE-M.wav"));

// show mels
~mels = Buffer(s);
FluidBufMelBands.processBlocking(s,~drums,features:~mels,numBands:512,windowSize:2048,action:{"done".postln});

// if you're on the right branch... (https://github.com/flucoma/flucoma-sc/tree/enhancement/FluidWaveform)
FluidWaveform(bounds:Rect(0,0,1600,400),rasterBuffer:~mels,rasterColorScheme:1);

// if not just look here:
(
~mels.loadToFloatArray(action:{
	arg mels;
	mels = mels.clump(~mels.numChannels);
	mels.dopostln;	
});
)

~mels.numChannels.postln;
```

**Comment by tremblap** [comment]
This is interesting and probably due to bands not having any bins at that level. This is a question for @g-roma for the behaviour of the algo, with a side one for @weefuzzy to see how the max plotter would act in this case (if any different). Also @tedmoore did you try to ask for 1 band per pixel and not more, so you avoid having empty channels-bands?

**Comment by tedmoore** [comment]
What I'm demonstrating is agnostic of pixels. This is happening at the `FluidBufMelBands` level. There are some channels in the buffer that are all zeros.

**Comment by tremblap** [comment]
I will need to try, as SC drawing is far from the best when pixel need under/oversampling (as I explained before).

Also, if your filters at the bottom don't have anything in them, they just don't. What I reckon iZotope is doing is smoothing.

At the moment I cannot test @weefuzzy because it draws in the wrong dimension. But I'll check values. This looks like Nicol, right?

**Comment by tedmoore** [comment]
Yep. It's Nicol.

**Comment by tremblap** [comment]
I thought it might be a bug, but I've check central frequencies of 512 bands between 20 and 20k like this:

```
(
~lowMel =  1127.010498 * ((20/700) + 1).log;
~highMel = 1127.010498 * ((20000/700) + 1).log;
~rangeMel = ~highMel - ~lowMel;
~stepMel = ~rangeMel / 513;
512.collect({
    arg i;
    var freqMel = (~stepMel * (i +1)) + ~lowMel;
    var freq = ((freqMel/ 1127.01048).exp - 1 ) * 700;
	freq;
});
)
```
and I get

24.729342702168, 29.489749912775, 34.281426006089, 39.104576372737, 43.959407752462, 48.846128242982, 53.764947308914, 58.716075790746, 63.699725913883, 68.716111297734, 73.765446964878, 78.847949350275, 83.963836310543, 89.113327133301, 94.296642546564, 99.514004728205, 104.76563731548, 110.05176541462, 115.37261561045, 120.72841597616, 126.11939608302, 131.54578701025, 137.00782135492, 142.50573324194, 148.03975833405, 153.61013384197, 159.21709853452, 164.86089274891, 170.541758401, 176.25993899567, 18...etc...

===
so it means that at the bottom there are 5Hz between the bands... at 2048 fft you get 22Hz between each bin. Now @g-roma  will have to let us know if that is an expected behaviour but for now, the number of pixel (which is the same as the number of mel bands you need on the y axis) could be made to match as the lower it is (with this implementation) the largest the distance betweem the melbands at the bottom so the lowest the fft oversampling will have to be.

to get 4 Hz, I needed to get the fft size above 11k, which I can do by windowSize:11000 or by oversampling the fft (fftSize: 16384) - the latter is slower but both yield no 0s.

Is it clear-ish? @g-roma am I understanding right?

**Comment by weefuzzy** [comment]
You'll get the same with librosa too, FWIW. Though they warn (the first time) about empty channels. 

```python
import librosa 
import librosa.display
import matplotlib.pyplot as plt
import numpy as np
y, sr = librosa.load('/Users/owen/dev/flucoma-core/AudioFiles/Nicol-LoopE-M.wav',sr=None)
S = librosa.feature.melspectrogram(y=y, sr=sr,n_mels=512)
fig, ax = plt.subplots()
S_dB = librosa.power_to_db(S, ref=np.max)
img = librosa.display.specshow(S_dB, x_axis='time',y_axis='mel', sr=sr,ax=ax)
fig.colorbar(img, ax=ax, format='%+2.0f dB')
ax.set(title='Mel-frequency spectrogram')
```

**Comment by tedmoore** [comment]
Throwing a warning seems like a fine solution.

Regarding the plotting, `FluidWaveform` won't know if the `imageBuffer` is composed of melBands, so it won't know that it should drop certain channels. I think if `FluidBufMelBands` documents the possibility for empty channels then the user can figure out why there are black bars. (and we can document it in the `FluidWaveform` examples as well).

**Comment by tedmoore** [comment]
> For now, can I suggest you oversample the fft for the drawings you need to do if that works for you, so you get to one band per pixel, check the space you need in Hz and oversample accordingly?

Yeah, I think this should be the use pattern when wanting to plot Mels.

**Comment by weefuzzy** [comment]
Well, unfortunately we can't warn at the moment because we have no mechanism to do it from wrapped real-time objects. But when we do 🥳 🎈 🎉 ✨

**Comment by tedmoore** [comment]
This can be closed when https://github.com/flucoma/flucoma-docs/pull/78 is merged.
