### ISSUE TITLE
Multiply defined symbols

### ISSUE THREAD

**Issue by MeijisIrlnd** [flucoma/flucoma-core#9]
Hiya, just wanted to have a mess around with using this library in a project, set up a really simple CMakeLists to compile my v basic code but on including TensorTypes I get that fluid::asUnsigned and fluid::asSigned are getting defined twice, any ideas? Is probably something dumb I'm doing, here's my cmake lists: 

> project(FluComaTest)
> cmake_minimum_required(VERSION 3.11)
> 
> set(INCLUDE_DIRS 
> ${CMAKE_SOURCE_DIR}/include/FluComa
> ${CMAKE_SOURCE_DIR}/include/eigen-src
> ${CMAKE_SOURCE_DIR}/include/hisstools-src
> )
> 
> set(LINK_LIBRARIES 
> ${CMAKE_SOURCE_DIR}/lib/HISSTools_AudioFile.lib 
> ${CMAKE_SOURCE_DIR}/lib/HISSTools_FFT.lib 
> )
> 
> set(SOURCE_FILES 
> ${CMAKE_SOURCE_DIR}/src/Extractors.cpp
> ${CMAKE_SOURCE_DIR}/src/main.cpp
> )
> 
> add_executable(main ${SOURCE_FILES})
> target_link_libraries(main ${LINK_LIBRARIES})
> target_include_directories(main PRIVATE ${INCLUDE_DIRS})
> set_target_properties(main PROPERTIES 
> CXX_STANDARD 14
> CXX_STANDARD_REQUIRED ON
> )

Edit: This error doesnt happen when you include the file in a main.cpp, but seems like an issue for projects with multiple classes and headers etc

**Comment by weefuzzy** [comment]
Hi @MeijisIrlnd, thanks for trying the project out and for letting us know. I think you may be the first person to try using this as an API, hence finding this problem! I'm pretty sure it's our fault: because the code is header-only, non-template functions need to be marked `inline` to avoid having multiple definitions when you have more than one translation unit. A quick survey with clang-tidy reveals that there's a few of these. 

So, an immediate remedy to your problem will be to edit `include/data/FluidIndex.hpp` and mark the two functions as `inline`. However, I'll try and push a more comprehensive fix very soon.

**Comment by MeijisIrlnd** [comment]
This is one for the Guinness Book of Records!!! Cheers for your speedy response will try this out later, looking forward to getting some sound through it!

**Comment by robclouth** [comment]
Hey! Just come across the same issue. I'm happy to submit a pull request to add ```inline``` to those methods.

**Comment by weefuzzy** [comment]
Hi @robclouth, that would be very welcome, thanks!

**Comment by robclouth** [comment]
@weefuzzy It's done!
